--------------------------------------------------------
--  파일이 생성됨 - 금요일-1월-11-2019   
--------------------------------------------------------
DROP SEQUENCE "SEMI"."SEQ_GROUP_NO";
DROP SEQUENCE "SEMI"."SEQ_SCHEDULE_NO";
DROP TABLE "SEMI"."FRIEND_GROUP";
DROP TABLE "SEMI"."MEMBER";
DROP TABLE "SEMI"."MEMBER_GROUP";
DROP TABLE "SEMI"."SCHEDULE";
DROP TABLE "SEMI"."UPLOADED_FILE";
--------------------------------------------------------
--  DDL for Sequence SEQ_GROUP_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SEMI"."SEQ_GROUP_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SCHEDULE_NO
--------------------------------------------------------

   CREATE SEQUENCE  "SEMI"."SEQ_SCHEDULE_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FRIEND_GROUP
--------------------------------------------------------

  CREATE TABLE "SEMI"."FRIEND_GROUP" 
   (	"GROUP_NO" NUMBER, 
	"GROUP_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEMI"."FRIEND_GROUP"."GROUP_NO" IS '시퀀스넘버';
   COMMENT ON COLUMN "SEMI"."FRIEND_GROUP"."GROUP_NAME" IS '그룹이름';
   COMMENT ON TABLE "SEMI"."FRIEND_GROUP"  IS '그룹테이블';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SEMI"."MEMBER" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PWD" VARCHAR2(200 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"MEMBER_GENDER" CHAR(1 BYTE) DEFAULT 'M', 
	"MEMBER_AGE" NUMBER, 
	"MEMBER_EMAIL" VARCHAR2(30 BYTE), 
	"MEMBER_LOGIN_LOG" NUMBER, 
	"MEMBER_STATUS" CHAR(1 BYTE) DEFAULT '1', 
	"MEMBER_SNS_ACCOUNT" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_ID" IS '회원아이디';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_PWD" IS '비밀번호';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_NAME" IS '회원이름';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_GENDER" IS '회원성별';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_AGE" IS '회원나이';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_EMAIL" IS '회원이메일';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_LOGIN_LOG" IS '로그인횟수';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_STATUS" IS '회원상태여부';
   COMMENT ON COLUMN "SEMI"."MEMBER"."MEMBER_SNS_ACCOUNT" IS 'sns연동';
   COMMENT ON TABLE "SEMI"."MEMBER"  IS '회원테이블';
--------------------------------------------------------
--  DDL for Table MEMBER_GROUP
--------------------------------------------------------

  CREATE TABLE "SEMI"."MEMBER_GROUP" 
   (	"GROUP_NO" NUMBER, 
	"MEMBER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEMI"."MEMBER_GROUP"."GROUP_NO" IS '시퀀스 넘버';
   COMMENT ON COLUMN "SEMI"."MEMBER_GROUP"."MEMBER_ID" IS '회원아이디';
   COMMENT ON TABLE "SEMI"."MEMBER_GROUP"  IS '친구그룹테이블';
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "SEMI"."SCHEDULE" 
   (	"SCHEDULE_NO" NUMBER, 
	"SCHEDULE_TITLE" VARCHAR2(50 BYTE), 
	"SCHEDULE_CONTENT" VARCHAR2(255 BYTE), 
	"SCHEDULE_ORIGINAL_FILENAME" VARCHAR2(30 BYTE), 
	"SCHEDULE_RENAMED_FILENAME" VARCHAR2(30 BYTE), 
	"SCHEDULE_DATE" DATE DEFAULT sysdate, 
	"SCHEDULE_DDAY_CHECK" CHAR(1 BYTE) DEFAULT 'N', 
	"SCHEDULE_REPEAT_CHECK" CHAR(1 BYTE) DEFAULT 'N', 
	"SCHEDULE_TIMELINE" NUMBER, 
	"SCHEDULE_START_DAY" DATE DEFAULT sysdate, 
	"SCHEDULE_END_DAY" DATE, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"SCHEDULE_DDAY" DATE, 
	"SCHEDULE_ICON" VARCHAR2(30 BYTE), 
	"THEDAY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_NO" IS '시퀀스넘버';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_TITLE" IS '스케줄제목';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_CONTENT" IS '스케줄내용';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_ORIGINAL_FILENAME" IS '기존파일이름';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_RENAMED_FILENAME" IS '저장할파일이름';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_DATE" IS '스케줄등록일';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_DDAY_CHECK" IS '디데이설정여부';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_REPEAT_CHECK" IS '스케줄반복여부';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_TIMELINE" IS '타임라인배치컬럼';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_START_DAY" IS '스케줄시작일';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."SCHEDULE_END_DAY" IS '스케줄종료일';
   COMMENT ON COLUMN "SEMI"."SCHEDULE"."MEMBER_ID" IS '회원아이디';
   COMMENT ON TABLE "SEMI"."SCHEDULE"  IS '스케줄 테이블';
--------------------------------------------------------
--  DDL for Table UPLOADED_FILE
--------------------------------------------------------

  CREATE TABLE "SEMI"."UPLOADED_FILE" 
   (	"SCHEDULE_NO" NUMBER, 
	"ORIGINAL_FILENAME" VARCHAR2(30 BYTE), 
	"RENAMED_FILENAME" VARCHAR2(30 BYTE), 
	"FILE_EXTENDER" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SEMI"."UPLOADED_FILE"."SCHEDULE_NO" IS '시퀀스넘버';
   COMMENT ON COLUMN "SEMI"."UPLOADED_FILE"."ORIGINAL_FILENAME" IS '기존파일이름';
   COMMENT ON COLUMN "SEMI"."UPLOADED_FILE"."RENAMED_FILENAME" IS '저장할파일이름';
   COMMENT ON COLUMN "SEMI"."UPLOADED_FILE"."FILE_EXTENDER" IS '파일확장자';
   COMMENT ON TABLE "SEMI"."UPLOADED_FILE"  IS '첨부파일 테이블';
REM INSERTING into SEMI.FRIEND_GROUP
SET DEFINE OFF;
REM INSERTING into SEMI.MEMBER
SET DEFINE OFF;
Insert into SEMI.MEMBER (MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_GENDER,MEMBER_AGE,MEMBER_EMAIL,MEMBER_LOGIN_LOG,MEMBER_STATUS,MEMBER_SNS_ACCOUNT) values ('abcde','1234','올라잇','M',121212,'803kkk@hanmail.net',null,'1',null);
Insert into SEMI.MEMBER (MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_GENDER,MEMBER_AGE,MEMBER_EMAIL,MEMBER_LOGIN_LOG,MEMBER_STATUS,MEMBER_SNS_ACCOUNT) values ('jsw4646','wkdtjsdnd1!','장선웅','M',19910814,'jsw4646@naver.com',null,'1',null);
Insert into SEMI.MEMBER (MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_GENDER,MEMBER_AGE,MEMBER_EMAIL,MEMBER_LOGIN_LOG,MEMBER_STATUS,MEMBER_SNS_ACCOUNT) values ('test2','Qv/eYm/+NtGh/QoxC9BiY1Ik0kWg3bz9oeFKS082gXGt7Uvlbs/8PW3wzHTwFvPbwlqhLLUN9UK6Wtg757pJfw==','올라잇','M',20020505,'test2@gmail.com',null,'1',null);
Insert into SEMI.MEMBER (MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_GENDER,MEMBER_AGE,MEMBER_EMAIL,MEMBER_LOGIN_LOG,MEMBER_STATUS,MEMBER_SNS_ACCOUNT) values ('test','7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==','tester','M',99,'test@na.kr',0,'1','페북');
Insert into SEMI.MEMBER (MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_GENDER,MEMBER_AGE,MEMBER_EMAIL,MEMBER_LOGIN_LOG,MEMBER_STATUS,MEMBER_SNS_ACCOUNT) values ('admin','x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ONxp3Y3pB37A==','관리자','M',99,'abc@na.kr',0,'1','페북');
Insert into SEMI.MEMBER (MEMBER_ID,MEMBER_PWD,MEMBER_NAME,MEMBER_GENDER,MEMBER_AGE,MEMBER_EMAIL,MEMBER_LOGIN_LOG,MEMBER_STATUS,MEMBER_SNS_ACCOUNT) values ('test3','jVO4ktmxNG18qwKoVFXNgH09Lc20YAxstWUHZOrHrNLPNkVkLuFimuyXYB9OXl+Wt9IcdqML6BKKbLsX22GBRg==','장그래','M',20190111,'test3@gmail.com',null,'1',null);
REM INSERTING into SEMI.MEMBER_GROUP
SET DEFINE OFF;
REM INSERTING into SEMI.SCHEDULE
SET DEFINE OFF;
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (22,'test','test','gosea3.png','20190110_151355929_890.png',to_date('19/01/08','RR/MM/DD'),'N','N',10,to_date('19/01/10','RR/MM/DD'),to_date('19/01/10','RR/MM/DD'),'test',null,null,8);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (41,'Scheduler 발표','개망 똥망',null,null,to_date('19/01/17','RR/MM/DD'),'N','N',0,to_date('19/01/11','RR/MM/DD'),to_date('19/01/17','RR/MM/DD'),'test2',null,null,17);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (42,'kh학원 수료','수료 끝!! 개이득 취업 뽀개자 !',null,null,to_date('19/03/12','RR/MM/DD'),'N','N',10,to_date('19/01/11','RR/MM/DD'),to_date('19/03/12','RR/MM/DD'),'test2',null,null,12);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (21,'테스트타이틀4','테스트콘텐트 내용4',null,null,to_date('19/01/09','RR/MM/DD'),'N','N',null,to_date('19/01/09','RR/MM/DD'),null,'admin',null,null,9);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (23,'test','test','gosea2.jpg','20190110_160626894_559.jpg',to_date('19/01/08','RR/MM/DD'),'Y','N',0,to_date('19/01/10','RR/MM/DD'),to_date('19/01/10','RR/MM/DD'),'test2',to_date('19/01/17','RR/MM/DD'),null,8);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (1,'테스트타이틀','테스트콘텐트 내용',null,null,to_date('19/01/08','RR/MM/DD'),'N','N',null,to_date('19/01/08','RR/MM/DD'),null,'admin',null,null,8);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (2,'테스트타이틀2','테스트콘텐트 내용2',null,null,to_date('19/01/08','RR/MM/DD'),'N','N',null,to_date('19/01/08','RR/MM/DD'),null,'admin',null,null,8);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (3,'테스트타이틀3','테스트콘텐트 내용3',null,null,to_date('19/01/08','RR/MM/DD'),'N','N',null,to_date('19/01/08','RR/MM/DD'),null,'admin',null,null,8);
Insert into SEMI.SCHEDULE (SCHEDULE_NO,SCHEDULE_TITLE,SCHEDULE_CONTENT,SCHEDULE_ORIGINAL_FILENAME,SCHEDULE_RENAMED_FILENAME,SCHEDULE_DATE,SCHEDULE_DDAY_CHECK,SCHEDULE_REPEAT_CHECK,SCHEDULE_TIMELINE,SCHEDULE_START_DAY,SCHEDULE_END_DAY,MEMBER_ID,SCHEDULE_DDAY,SCHEDULE_ICON,THEDAY) values (43,'처음으로 7스케줄러 가입한날!','찡긋?~!
still need you - uplink곡 개좋당 ㅎㅎ',null,null,to_date('19/01/11','RR/MM/DD'),'N','N',7,to_date('19/01/11','RR/MM/DD'),to_date('19/01/11','RR/MM/DD'),'test3',null,null,11);
REM INSERTING into SEMI.UPLOADED_FILE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_FRIEND_GROUP_GROUP_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."PK_FRIEND_GROUP_GROUP_NO" ON "SEMI"."FRIEND_GROUP" ("GROUP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_MEMBER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."PK_MEMBER_MEMBER_ID" ON "SEMI"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCHEDULE_SCHEDULE_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMI"."PK_SCHEDULE_SCHEDULE_NO" ON "SEMI"."SCHEDULE" ("SCHEDULE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FRIEND_GROUP
--------------------------------------------------------

  ALTER TABLE "SEMI"."FRIEND_GROUP" ADD CONSTRAINT "PK_FRIEND_GROUP_GROUP_NO" PRIMARY KEY ("GROUP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEMI"."FRIEND_GROUP" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."FRIEND_GROUP" MODIFY ("GROUP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SEMI"."MEMBER" ADD CONSTRAINT "PK_MEMBER_MEMBER_ID" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_AGE" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_GENDER" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_PWD" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_GROUP
--------------------------------------------------------

  ALTER TABLE "SEMI"."MEMBER_GROUP" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."MEMBER_GROUP" MODIFY ("GROUP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SEMI"."SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE_SCHEDULE_NO" PRIMARY KEY ("SCHEDULE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEMI"."SCHEDULE" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SEMI"."SCHEDULE" MODIFY ("SCHEDULE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UPLOADED_FILE
--------------------------------------------------------

  ALTER TABLE "SEMI"."UPLOADED_FILE" MODIFY ("SCHEDULE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_GROUP
--------------------------------------------------------

  ALTER TABLE "SEMI"."MEMBER_GROUP" ADD CONSTRAINT "FK_MEMBER_GROUP_GROUP_NO" FOREIGN KEY ("GROUP_NO")
	  REFERENCES "SEMI"."FRIEND_GROUP" ("GROUP_NO") ENABLE;
  ALTER TABLE "SEMI"."MEMBER_GROUP" ADD CONSTRAINT "FK_MEMBER_GROUP_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SEMI"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SEMI"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SEMI"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UPLOADED_FILE
--------------------------------------------------------

  ALTER TABLE "SEMI"."UPLOADED_FILE" ADD CONSTRAINT "FK_UPLOADED_FILE_SCHEDULE_NO" FOREIGN KEY ("SCHEDULE_NO")
	  REFERENCES "SEMI"."SCHEDULE" ("SCHEDULE_NO") ENABLE;
