/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-16 10:35:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recommendation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<<<<<<< HEAD\r\n");
      out.write("\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Alfa+Slab+One|Staatliches|Noto+Sans+KR|Abril+Fatface\" rel=\"stylesheet\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo(favicon).png\" type=\"image/png\" sizes=\"128x128\">\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/recommendation.css\" />\r\n");
      out.write("<title>온도에 따른 추천 의상, 여행지</title>\r\n");
      out.write("\r\n");

	String temp = request.getParameter("temp");
	
	System.out.println("시험하는곳 temp = "+temp);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("div.container{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:29%;\r\n");
      out.write("\theight:300px;\r\n");
      out.write("\tmaring:10px;\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("\tborder:1px solid;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("td,th {\r\n");
      out.write("\tborder:1px solid;\r\n");
      out.write("}\r\n");
      out.write("span#time{\r\n");
      out.write("\ttext-decoration:underline;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("#order-list{\r\n");
      out.write("\twidth:80%;\r\n");
      out.write("\tmargin-left:50px;\r\n");
      out.write("}\r\n");
      out.write("#rank-list{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo.png\" width=\"50px\" height=\"50px\" >\r\n");
      out.write("      <span class=\"logofont\">7' Scheduler\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container2\">\r\n");
      out.write("\t<h2>추천 의상</h2>\r\n");
      out.write("\t<div id=\"order-list\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("function printTime() {\r\n");
      out.write("      var time = document.getElementById(\"time\");            // 출력할 장소 선택\r\n");
      out.write("      var now = new Date();                                                  // 현재시간\r\n");
      out.write("      var nowTime = now.getFullYear() + \"년 \" + (now.getMonth()+1) + \"월 \" + now.getDate() + \"일 \" + now.getHours() + \"시 \" + now.getMinutes() + \"분 \" + now.getSeconds() + \"초\";\r\n");
      out.write("\r\n");
      out.write("      time.innerHTML = nowTime;           // 현재시간을 출력\r\n");
      out.write("\r\n");
      out.write("      setTimeout(\"printTime()\",1000);         // setTimeout(“실행할함수”,시간) 시간은1초의 경우 1000\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container2\">\r\n");
      out.write("\t<h2>추천 장소</h2>\r\n");
      out.write("\t<h4 id=\"time\"></h4>\r\n");
      out.write("\t<div id=\"rank-list\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\t   \r\n");
      out.write("\t<script>\r\n");
      out.write("\twindow.onload =function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/temperature/recdress.do\",\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: \"temp=\"+");
      out.print(temp);
      out.write(",\r\n");
      out.write("\t\t\tsuccess: function (data) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(data); //data는 이미 javascript배열객체\r\n");
      out.write("\t\t\t\t//json <----> javascript\r\n");
      out.write("\t\t\t\t//\t   <--- JSON.stringgify()\r\n");
      out.write("\t\t\t\t//\t  \t---> JSON.parse()\r\n");
      out.write("\t\t\t\tvar table = $(\"<table id='cloth'></table>\");\r\n");
      out.write("\t\t\t\tvar html = \"<tr><th>온도</th><th colspan=2>추천내용</th></tr>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print(temp);
      out.write(" <= 4){\r\n");
      out.write("                    html += \"<tr><td>~4˚C</td>\";\r\n");
      out.write("                    html += \"<td>겨울 옷 (패딩, 두꺼운코트, 목도리, 기모제품 )</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/4~.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if((");
      out.print(temp);
      out.write(" > 4)&&(");
      out.print(temp);
      out.write(" <= 8)){\r\n");
      out.write("                    html += \"<tr><td>5˚C~8˚C</td>\";\r\n");
      out.write("                    html += \"<td>코트, 가죽자켓, 히트텍, 니트, 레깅스</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/8~5.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if((");
      out.print(temp);
      out.write(" > 8)&&(");
      out.print(temp);
      out.write(" <= 11)){\r\n");
      out.write("                    html += \"<tr><td>9˚C~11˚C</td>\";\r\n");
      out.write("                    html += \"<td>자켓, 트렌치코트, 야상, 니트, 청.면바지</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/11~9.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if((");
      out.print(temp);
      out.write(" > 11)&&(");
      out.print(temp);
      out.write(" <= 16)){\r\n");
      out.write("                    html += \"<tr><td>12˚C~16˚C</td>\";\r\n");
      out.write("                    html += \"<td>자켓, 가디건, 야상, 청.면바지</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/16~12.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if((");
      out.print(temp);
      out.write(" > 16)&&(");
      out.print(temp);
      out.write(" <= 19)){\r\n");
      out.write("                    html += \"<tr><td>17˚C~19˚C</td>\";\r\n");
      out.write("                    html += \"<td>얇은니트, 맨투맨, 가디너, 청바지</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/19~17.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if((");
      out.print(temp);
      out.write(" > 19)&&(");
      out.print(temp);
      out.write(" <= 22)){\r\n");
      out.write("                    html += \"<tr><td>20˚C~22˚C</td>\";\r\n");
      out.write("                    html += \"<td>얇은 가디건, 긴팔, 청.면바지</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/22~10.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if((");
      out.print(temp);
      out.write(" > 22)&&(");
      out.print(temp);
      out.write(" <= 27)){\r\n");
      out.write("                    html += \"<tr><td>23˚C~27˚C</td>\";\r\n");
      out.write("                    html += \"<td>반팔, 얇은셔츠, 반바지</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/27~23.png'/></td></tr>\";\r\n");
      out.write("                    \r\n");
      out.write("                }else if(");
      out.print(temp);
      out.write(" >= 28){\r\n");
      out.write("                    html += \"<tr><td>28˚C~</td>\";\r\n");
      out.write("                    html += \"<td>민소매, 반팔, 반바지 , 원피스</td>\";\r\n");
      out.write("                    html += \"<td><img src='");
      out.print(request.getContextPath());
      out.write("/images/cloth/~28.png'/></td></tr>\";\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttable.append(html);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#order-list\").html(table);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function (jqxhr, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/temperature/rectour.do\",\r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tdata: \"temp=\"+");
      out.print(temp);
      out.write(",\r\n");
      out.write("\t\t\tsuccess: function (data) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(data); //data는 이미 javascript배열객체\r\n");
      out.write("\t\t\t\t//json <----> javascript\r\n");
      out.write("\t\t\t\t//\t   <--- JSON.stringgify()\r\n");
      out.write("\t\t\t\t//\t  \t---> JSON.parse()\r\n");
      out.write("\t\t\t\tvar table = $(\"<table></table>\");\r\n");
      out.write("\t\t\t\tvar html = \"<tr><th>온도</th><th>추천내용</th></tr>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print(temp);
      out.write(" <= 4){\r\n");
      out.write("\t\t\t\t\thtml += \"<tr><td>~4˚C</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>실내에서 노시는게 좋을겁니다^^</td></tr>\";\r\n");
      out.write("\t\t\t\t}else if(");
      out.print(temp);
      out.write(" > 10)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\thtml += \"<tr><td>10˚C</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>밖에서 노시죠^^</td></tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttable.append(html);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#rank-list\").html(table);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function (jqxhr, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\tconsole.log(jqxhr);\r\n");
      out.write("\t\t\t\tconsole.log(textStatus);\r\n");
      out.write("\t\t\t\tconsole.log(errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
