/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-10 17:47:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sendMailpopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    	int certifiedNum = (int)request.getAttribute("certified");
    	System.out.println(certifiedNum);

    
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>이메일 인증</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function check(){\r\n");
      out.write("\tvar certified = $(\"#certified\").val().trim();\r\n");
      out.write("\tconsole.log(certified);\r\n");
      out.write("\tvar certifiedNum = ");
      out.print(certifiedNum);
      out.write(";\r\n");
      out.write("\tconsole.log(certifiedNum);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(certified.length == 0){\r\n");
      out.write("\t\talert(\"인증번호를 입력하세요\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else if(certified != certifiedNum){\r\n");
      out.write("\t\talert(\"인증번호가 틀렸습니다. 인증번호를 다시입력해주세요.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"인증 완료\");\r\n");
      out.write("\t\topener.signupform.target.value = \"1\";\r\n");
      out.write("\t\topener.signupform.emailclear.value = \"인증완료\";\r\n");
      out.write("\t\topener.signupform.memberEmail.readOnly = \"true\";\r\n");
      out.write("\t\topener.signupform.emailclear.disabled=\"true\";\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tself.close();\r\n");
      out.write("\t}\r\n");
      out.write("} \r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#emailcertified-container{\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("\twidth: 340px;\r\n");
      out.write("\theight:130px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("#emailcertified-container label{\r\n");
      out.write("\tmargin: 0px auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop:50px;\r\n");
      out.write("\tleft:25px;\r\n");
      out.write("}\r\n");
      out.write("#emailcertified-container #certified{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop:50px;\r\n");
      out.write("\tleft:25px;\r\n");
      out.write("}\r\n");
      out.write("#emailcertified-container #check{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop:52px;\r\n");
      out.write("\tbackground-color: rgba(142, 40, 170, 0.65);\r\n");
      out.write("    color: rgb(248, 248, 248);\r\n");
      out.write("    border: 0;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    left:25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"emailcertified-container\">\r\n");
      out.write("\t\t<label for=\"certified\">인증번호 : </label>\r\n");
      out.write("\t\t<input type=\"textname=\"certified\" id=\"certified\"/>\r\n");
      out.write("\t\t<input type=\"button\" value=\"확인\" id=\"check\" onclick=\"check();\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
