/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-17 07:01:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.kh.member.model.vo.*;
import com.kh.member.model.vo.*;
import java.util.List;
import com.kh.member.model.vo.Member;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1547707298866L));
    _jspx_dependants.put("/WEB-INF/views/common/side.jsp", Long.valueOf(1547708101594L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.kh.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");

	Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");  


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Alfa+Slab+One|Staatliches|Noto+Sans+KR|Abril+Fatface\" rel=\"stylesheet\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\">\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo(favicon).png\" type=\"image/png\" sizes=\"128x128\">\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body oncontextmenu=\"return false;\">\r\n");
      out.write("  <nav class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("      <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/logo.png\" width=\"50px\" height=\"50px\" >\r\n");
      out.write("      <span class=\"logofont\">7' Scheduler\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>  \r\n");
      out.write("\r\n");
      out.write("   ");
if(memberLoggedIn != null){ 
      out.write("\r\n");
      out.write("  <table id=\"logged-in\" >\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t ");
      out.print(memberLoggedIn.getMemberName() );
      out.write("님,\t안녕하세요 :)\t\t \r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"mypage\" value=\"내정보\" onclick='location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/MemberView?memberId=");
      out.print(memberLoggedIn.getMemberId());
      out.write("\";'/>\r\n");
      out.write("\t\t\t&nbsp;\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"logout\" value=\"로그아웃\" onclick=\"logout();\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\t\r\n");
      out.write("\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </nav>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(\".logo\").click(function(){\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function logout(){\r\n");
      out.write("\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("/member/logout\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member memberLoggedIn1 = (Member)session.getAttribute("memberLoggedIn");  
	List<String> friendList = null;
	
	if(memberLoggedIn1 == null) {
		
	} else {
		try {
			friendList = (List)session.getAttribute("friendList");
		} catch(NullPointerException e) {
			
		}
	}
	
	


      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Alfa+Slab+One|Staatliches|Noto+Sans+KR|Abril+Fatface\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Coiny|Do+Hyeon|Gothic+A1|Nanum+Gothic+Coding|Nanum+Pen+Script|Noto+Sans+KR\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/side.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".fnd:hover{\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  function showPopup(temp) {\r\n");
      out.write("\t  var windowW = 500;  // 창의 가로 길이\r\n");
      out.write("      var windowH = 400;  // 창의 세로 길이\r\n");
      out.write("      var left = Math.ceil((window.screen.width - windowW)/2);\r\n");
      out.write("      var top = Math.ceil((window.screen.height - windowH)/2);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  window.open(\"");
      out.print(request.getContextPath() );
      out.write("/member/recommendation?temp=\"+temp, \"a\",\"l top=\"+top+\", left=\"+left+\", height=\"+windowH+\", width=\"+windowW); \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("  }\r\n");
      out.write("  function addfriend(){\r\n");
      out.write("\t$(\"#friends\").css('display','inline-block');\t  \r\n");
      out.write("  }\r\n");
      out.write("  function close(){\r\n");
      out.write("\t$(\"#friends\").css('display','none');\t  \r\n");
      out.write("\t  \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  window.onload =function(){\r\n");
      out.write(" \r\n");
      out.write("\tvar apiURI = \"http://api.openweathermap.org/data/2.5/weather?q=Seoul&appid=c95231fca9f07b22a6540efdcce37587\";\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: apiURI,\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        type: \"GET\",\r\n");
      out.write("        async: \"false\",\r\n");
      out.write("        success: function(resp) {\r\n");
      out.write("        \tvar myDiv = document.getElementById(\"myDiv\"); \r\n");
      out.write("        \tvar table = $(\"<table></table>\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\thtml = \"<br><br>현재온도 : \"+Math.floor((resp.main.temp- 273.15))+\"도<br>\";\r\n");
      out.write("\t\t\thtml += \"날씨 : \"+resp.weather[0].description+\"<br>\";\r\n");
      out.write("\t\t\thtml += \"나라 : \"+resp.sys.country+\"<br>\";\r\n");
      out.write("\t\t\thtml +=\t\"도시 이름 : \"+resp.name+\"<br>\";\r\n");
      out.write("\t\t\thtml += \"구름 : \"+(resp.clouds.all)+\"%<br>\";\r\n");
      out.write("\t\t\thtml += \"<input type='button' id='weatherbtn' value='추천 여행,의상 보기' onclick= 'showPopup(\"+(resp.main.temp- 273.15)+\");'/>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmyDiv.innerHTML = html;\r\n");
      out.write("\t\t\t\r\n");
      out.write("            //console.log(resp);\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            /* console.log(\"현재온도 : \"+ (resp.main.temp- 273.15) );\r\n");
      out.write("            console.log(\"현재습도 : \"+ resp.main.humidity);\r\n");
      out.write("            console.log(\"날씨 : \"+ resp.weather[0].main );\r\n");
      out.write("            console.log(\"상세날씨설명 : \"+ resp.weather[0].description );\r\n");
      out.write("            console.log(\"날씨 이미지 : \"+ resp.weather[0].icon );\r\n");
      out.write("            console.log(\"바람   : \"+ resp.wind.speed );\r\n");
      out.write("            console.log(\"나라   : \"+ resp.sys.country );\r\n");
      out.write("            console.log(\"도시이름  : \"+ resp.name );\r\n");
      out.write("            console.log(\"구름  : \"+ (resp.clouds.all) +\"%\" );   */              \r\n");
      out.write("        \t}\r\n");
      out.write("    \t})    \t\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"side\">\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<div id=\"searchsch\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"font\" id=\"yearSchedule\">연간 스케줄</a><hr />\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/mainSchedule\" class=\"font\">월간 스케줄</a><hr />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/schedule/schedulelist\" class=\"font\">스케줄 찾기</a><hr />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 if(memberLoggedIn1 != null && "admin".equals(memberLoggedIn1.getMemberId())){
      out.write("\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberList\" class=\"font\">회원리스트</a><br />\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"myDiv\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"friend\">\r\n");
      out.write("\t\t\t<p>친구\r\n");
      out.write("\t\t\t<button id=\"friendList\" \">∨</button>\r\n");
      out.write("\t\t\t<button id=\"addfriend\" onclick=\"addfriend();\">+</button></p>\r\n");
      out.write("\t\t\t<div id=\"friendspace\">\r\n");
      out.write("\t\t\t\t");
 if(friendList != null && !friendList.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 for(int i = 0;i < friendList.size();i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<span class=\"fnd\" id=\"");
      out.print(friendList.get(i));
      out.write('"');
      out.write('>');
      out.print(friendList.get(i) );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t");
 } 
				} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<span>친구가 <br />없으십니다.</span>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"friends\">\r\n");
      out.write("\t\t<form class=\"insertFriendFrm\" name=\"insertFriendFrm\"\r\n");
      out.write("\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/friend/insertFriendQueue\" \r\n");
      out.write("\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"myId\" id=\"myId\" value=\"");
      out.print(memberLoggedIn1.getMemberId() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t<label for=\"srchId\" id=\"font2\">아이디 : </label>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"text\"  name=\"srchId\" id=\"srchId\" autocomplete=\"off\" />\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<ul id=\"autoComplete\">\r\n");
      out.write("\t\t\t\t\t\t<li>1</li>\r\n");
      out.write("\t\t\t\t\t\t<li>2</li>\r\n");
      out.write("\t\t\t\t\t\t<li>3</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"self.close();\" value=\"취소\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t\t<button id=\"friendadd\" onclick=\"checkId();\">친구 추가</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("     \t<form action=\"");
      out.print(request.getContextPath());
      out.write("/chat/chatpopup\"\r\n");
      out.write("      \tmethod=\"post\"\r\n");
      out.write("      \tname=\"chatFrm\">\r\n");
      out.write("      \t<input type=\"hidden\" id=\"fromId\" name=\"fromId\" value=\"");
      out.print(memberLoggedIn1.getMemberId());
      out.write("\" />\r\n");
      out.write("      \t<input type=\"hidden\" id=\"toId\" name=\"toId\" />\r\n");
      out.write("      \t</form>\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#friendList\").on('click',function(){\r\n");
      out.write("\t$(\"#friendspace\").slideToggle(\"fast\");\r\n");
      out.write("});\r\n");
      out.write("$(\"#srchId\").on(\"keyup\" , function(e){\r\n");
      out.write("\tconsole.log(e.key);\r\n");
      out.write("\tvar selected = $(\".selected\");\r\n");
      out.write("\tvar li = $(\"#autoComplete li\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(e.key == \"ArrowDown\") {\r\n");
      out.write("\t\tif(selected.length == 0) {\r\n");
      out.write("\t\t\t$(\"#autoComplete li:first\").addClass(\"selected\");\r\n");
      out.write("\t\t} else if(selected.is(li.last())) {\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tselected.removeClass(\"selected\").next().addClass(\"selected\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} else if(e.key == \"ArrowUp\") {\r\n");
      out.write("\t\tif(selected.length == 0) {\r\n");
      out.write("\t\t} else if(selected.is(li.first())) {\r\n");
      out.write("\t\t\tselected.removeClass(\"selected\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tselected.removeClass(\"selected\").prev().addClass(\"selected\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} else if(e.key == \"Enter\") {\r\n");
      out.write("\t\t$(this).val(selected.text());\r\n");
      out.write("\t\t$(\"#autoComplete\").hide().children().remove();\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tvar srchId = $(this).val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(srchId.length == 0) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/friend/autoComplete.do\" ,\r\n");
      out.write("\t\t\ttype: \"post\" ,\r\n");
      out.write("\t\t\tdata: {srchId:srchId} ,\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar idArr = data.split(\",\");\r\n");
      out.write("\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\tfor(var i = 0;i < idArr.length;i++) {\r\n");
      out.write("\t\t\t\t\thtml += \"<li>\"+idArr[i].replace(srchId,\"<span class='srchVal'>\"+srchId+\"</span>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data.length != 0) {\r\n");
      out.write("\t\t\t\t\t$(\"#autoComplete\").html(html).css(\"display\" , \"inline-block\");\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#autoComplete\").hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#autoComplete\").on(\"click\" , \"li\" , function(){\r\n");
      out.write("\t$(\"#srchId\").val($(this).text());\r\n");
      out.write("\t$(\"#autoComplete\").hide().children().remove();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#autoComplete\").on(\"mouseenter\" , \"li\" , function() {\r\n");
      out.write("\t$(this).siblings().removeClass(\"selected\");\r\n");
      out.write("\t$(this).addClass(\"selected\");\r\n");
      out.write("});\r\n");
      out.write("$(\"#autoComplete\").on(\"mouseleave\" , \"li\" , function() {\r\n");
      out.write("\t$(this).removeClass(\"selected\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function checkId(){\r\n");
      out.write("\t  var srchId = $(\"#srchId\").val().trim();\r\n");
      out.write("\t  if(srchId.length == 0){\r\n");
      out.write("\t\t  alert(\"검색하실 아이디를 선택하거나 입력해주세요.\");\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  //팝업창을 target으로 폼전송\r\n");
      out.write("\t\tvar target = \"insertFriendFrm\";\r\n");
      out.write("\t\t//첫번째 인자 url은 생략, form의 action값이 이를 대신한다.\r\n");
      out.write("\t\tvar popup = open(\"\", target, \"left=300px, top=100px, height=135px, width=470px\");\r\n");
      out.write("\t\t//폼의 대상을 작성한 popup을 가리키게 한다. \r\n");
      out.write("\t\tinsertFriendFrm.target = target;\r\n");
      out.write("\t\tinsertFriendFrm.submit();\t\t\r\n");
      out.write("\t  }\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("/* 채팅관련 스크립트 */\r\n");
      out.write("function chatOpen(){\r\n");
      out.write("    var target = \"chatpopup\";\r\n");
      out.write("    var popup = open(\"\", target, \"left=400px, top=150px, height=540px, width=500px , resizable=no, scrollbars=no, status=no;\");\r\n");
      out.write("    chatFrm.target = target;\r\n");
      out.write("    chatFrm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var toId;\r\n");
      out.write("$(\".fnd\").on(\"click\" , function(){\t\r\n");
      out.write("\ttoId = $(this).attr(\"id\");\r\n");
      out.write("\t$(\"#toId\").attr(\"value\",toId);\r\n");
      out.write("\tconsole.log(\"#toId value값 확인 : \"+$(\"#toId\").val());\r\n");
      out.write("\tchatOpen();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
	
	List<Member> list = (List<Member>)request.getAttribute("list");
	int cPage = (int)request.getAttribute("cPage");
	int numPerPage = (int)request.getAttribute("numPerPage");
	String pageBar = (String)request.getAttribute("pageBar");
	

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/memberList.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Pen+Script\" rel=\"stylesheet\">\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans\" rel=\"stylesheet\">\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar memberId = $(\"#search-memberId\");\t\r\n");
      out.write("\tvar memberName = $(\"#search-memberName\");\r\n");
      out.write("\tvar memberLoginglog = $(\"#search-memberLoginlog\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"select#searchType\").change(function(){\r\n");
      out.write("\t\tmemberId.hide();\r\n");
      out.write("\t\tmemberName.hide();\r\n");
      out.write("\t\tmemberLoginglog.hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#search-\"+$(this).val()).css(\"display\",\"inline-block\");\r\n");
      out.write("\t});\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<section id=\"member-container\">\t\r\n");
      out.write("<h2>회원 리스트</h2>\t\r\n");
      out.write("\t\t검색:&nbsp;&nbsp;\r\n");
      out.write("\t\t<select id=\"searchType\">\r\n");
      out.write("\t\t\t<option value=\"memberId\">아이디</option>\r\n");
      out.write("\t\t\t<option value=\"memberName\">이름</option>\r\n");
      out.write("\t\t\t<option value=\"memberLoginlog\">로그인횟수</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<div id=\"search-memberId\">\t\t\t\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberSearch\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchType\"\r\n");
      out.write("\t\t\t\t\t   value=\"memberId\" />\r\n");
      out.write("\t\t\t\t<input type=\"search\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\r\n");
      out.write("\t\t\t\t\t   size=\"25\"\r\n");
      out.write("\t\t\t\t\t   placeholder=\"검색할 아이디를 입력하세요.\"/>&nbsp;\r\n");
      out.write("\t\t\t\t<button type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search-memberName\">\t\t\t\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberSearch\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchType\"\r\n");
      out.write("\t\t\t\t\t   value=\"memberName\" />\r\n");
      out.write("\t\t\t\t<input type=\"search\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\r\n");
      out.write("\t\t\t\t\t   size=\"25\"\r\n");
      out.write("\t\t\t\t\t   placeholder=\"검색할 이름을 입력하세요.\"/>&nbsp;\r\n");
      out.write("\t\t\t\t<button type=\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search-memberLoginlog\">\t\t\t\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/admin/memberSearch\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchType\"\r\n");
      out.write("\t\t\t\t\t   value=\"memberLoginlog\" />\r\n");
      out.write("\t\t\t\t<input type=\"search\" \r\n");
      out.write("\t\t\t\t\t   name=\"searchKeyword\"\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t   size=\"25\"\r\n");
      out.write("\t\t\t\t\t   placeholder=\"접속횟수 순위\"\r\n");
      out.write("\t\t\t\t\t   readonly />\t&nbsp;\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"btn\">검색</button>\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<section id=\"memberList-container\">\t\t\r\n");
      out.write("\t<table id=\"tbl-memberList\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>번호</th>\r\n");
      out.write("\t\t<th>아이디</th>\r\n");
      out.write("\t\t<th>이름</th>\r\n");
      out.write("\t\t<th>성별</th>\r\n");
      out.write("\t\t<th>나이</th>\r\n");
      out.write("\t\t<th>이메일</th>\r\n");
      out.write("\t\t<th>로그인횟수</th>\r\n");
      out.write("\t\t<th>상태</th>\r\n");
      out.write("\t\t<th>SNS연동</th>\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<!-- 스크립틀릿 처리요망 -->\r\n");
      out.write("\t");
 if(list == null || list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t검색결과가 없습니다.\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");
} 
	else {
		int index=0;
		for(Member m : list){
			index++;			
	
      out.write("\t\t\t\r\n");
      out.write("\t\t<tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print((cPage-1)*7+index);
      out.write("</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberId());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberName());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberGender());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberAge());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberEmail());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberLoginlog());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberStatus());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t<td>");
      out.print(m.getMemberSnsaccount());
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");
 }
	} 
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"pageBar\">\r\n");
      out.write("\t");
      out.print(pageBar );
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
